bot:
  token: 6987300064:AAHiH7jBLVCCrSvcrgc2YEmpXonbtspjdjA

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.client.endpoint: DEBUG

loginUrl: https://e192-194-44-97-79.ngrok-free.app/login/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatAggregation
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          olx:
            client-id: 201729
            client-secret: ePnHSRdWSoMPV9rEbDPyjuWg7266ZQ1CaXq5xYZByDl11e4Q
            redirect-uri: https://e192-194-44-97-79.ngrok-free.app/login/oauth2/code/olx
            scope: v2+read+write
            authorization-grant-type: authorization_code
            client-name: OLX
        provider:
          olx:
            authorization-uri: https://www.olx.ua/oauth/authorize/
            token-uri: https://www.olx.ua/api/open/oauth/token/
            user-info-uri: https://www.olx.ua/api/partner/users/me
            user-name-attribute: "name"

  jackson:
    serialization:
      fail-on-empty-beans: false
